---
- name: Ansible Service Setup
  hosts: all
  become: yes
  roles:
    - { role: roles/pip_installer, tags: 'pip-install' }
    - { role: roles/apt_installer, tags: 'apt-install' }
    - { role: roles/fact_gatherer, tags: 'gather-facts' }
